/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error": "#ffb4ab",
        "surface-bright": "#3e392f",
        "on-background": "#ebe1d3",
        "primary-fixed": "#ffdf95",
        "on-error": "#690005",
        "on-tertiary-container": "#005e74",
        "surface-container-highest": "#39342a",
        "on-surface-variant": "#d1c5ae",
        "surface-variant": "#39342a",
        "on-secondary-fixed-variant": "#474746",
        "error-container": "#93000a",
        "outline-variant": "#4e4634",
        "on-tertiary": "#003544",
        "on-primary-fixed-variant": "#594400",
        "primary-fixed-dim": "#f0c03e",
        "on-secondary-fixed": "#1c1b1b",
        "surface-container-high": "#2e2920",
        "on-surface": "#ebe1d3",
        "inverse-on-surface": "#353026",
        "surface-dim": "#17130b",
        "on-tertiary-fixed-variant": "#004d61",
        "surface-container-lowest": "#110e06",
        "on-primary-container": "#6b5200",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#ebe1d3",
        "on-primary": "#3e2e00",
        "secondary-fixed": "#e5e2e1",
        "outline": "#9a907b",
        "tertiary": "#c5eeff",
        "background": "#17130b",
        "secondary-fixed-dim": "#c8c6c5",
        "primary-container": "#f5c542",
        "primary": "#ffe5aa",
        "tertiary-fixed": "#b8eaff",
        "surface": "#17130b",
        "on-primary-fixed": "#251a00",
        "tertiary-fixed-dim": "#63d4fa",
        "on-tertiary-fixed": "#001f28",
        "secondary": "#c8c6c5",
        "surface-container": "#231f16",
        "surface-tint": "#f0c03e",
        "surface-container-low": "#1f1b12",
        "on-secondary": "#313030",
        "secondary-container": "#474746",
        "on-secondary-container": "#b7b5b4",
        "inverse-primary": "#765a00",
        "tertiary-container": "#69d9ff",
        "gold": "#F5C542",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "container-max": "1280px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "section-gap": "120px",
        "margin-mobile": "20px",
        "stack-sm": "8px",
        "unit": "8px",
        "gutter": "24px"
      },
      fontFamily: {
        "manrope": ["Manrope", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "display-xl": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-xl": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }]
      }
    },
  },
  plugins: [],
}